tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "weaveworks/tap"
brew "readline"
brew "ansible"
brew "asdf"
brew "aws-iam-authenticator"
brew "bat"
brew "broot"
brew "glib"
brew "cask"
brew "deno"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "git-secrets"
brew "gitui"
brew "go"
brew "grex"
brew "hub"
brew "tcl-tk"
brew "imagemagick"
brew "ios-deploy"
brew "jpegoptim"
brew "krb5"
brew "kubernetes-cli"
brew "libmagic"
brew "mas"
brew "neovim"
brew "nkf"
brew "optipng"
brew "pandoc"
brew "peco"
brew "poppler"
brew "python-yq"
brew "ripgrep"
brew "ripgrep-all"
brew "ruby"
brew "sdl2"
brew "sdl2_image"
brew "silicon"
brew "sl"
brew "starship"
brew "tealdeer"
brew "telnet"
brew "tesseract"
brew "tesseract-lang"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "z"
brew "zsh"
brew "heroku/brew/heroku"
brew "weaveworks/tap/eksctl"
cask "1password"
cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "deepl"
cask "docker"
cask "drawio"
cask "figma"
cask "font-cica"
cask "font-hack-nerd-font"
cask "github"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "kitty"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "miro"
cask "ngrok"
cask "notion"
cask "postman"
cask "raycast"
cask "slack"
cask "spotify"
cask "tableplus"
cask "ticktick"
cask "visual-studio-code"
cask "wezterm"
cask "zeplin"
cask "zoom"
mas "GarageBand", id: 682658836
mas "Hidden Bar", id: 1452453066
mas "HotKey", id: 975890633
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Logic Pro", id: 634148309
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Playgrounds", id: 1496833156
mas "RunCat", id: 1429033973
mas "Transporter", id: 1450874784
mas "Xcode", id: 497799835
