tap 'heroku/brew'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'weaveworks/tap'

brew 'aws-iam-authenticator'
brew 'deno'
brew 'exa'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'ghostscript'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'git-lfs'
brew 'git-secrets'
brew 'readline'
brew 'glib'
brew 'go'
brew 'hub'
brew 'tcl-tk'
brew 'imagemagick'
brew 'ios-deploy'
brew 'jpegoptim'
brew 'krb5'
brew 'kubernetes-cli'
brew 'libmagic'
brew 'mas'
brew 'neovim'
brew 'nkf'
brew 'nodenv'
brew 'optipng'
brew 'peco'
brew 'postgresql', restart_service: true
brew 'postgresql@11', restart_service: true
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python-yq'
brew 'ruby-build'
brew 'rbenv'
brew 'ruby'
brew 'sdl2'
brew 'sdl2_image'
brew 'sl'
brew 'telnet'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'z'
brew 'zsh'
brew 'heroku/brew/heroku'
brew 'weaveworks/tap/eksctl'

cask '1password'
cask 'alfred'
cask 'app-cleaner'
cask 'deepl'
cask 'docker'
cask 'drawio'
cask 'figma'
cask 'font-hack-nerd-font'
cask 'github'
cask 'google-chrome'
cask 'iterm2'
cask 'microsoft-auto-update'
cask 'microsoft-excel'
cask 'miro'
cask 'ngrok'
cask 'notion'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'ticktick'
cask 'visual-studio-code'
cask 'zeplin'
cask 'zoom'

mas 'GarageBand', id: 682_658_836
mas 'Hidden Bar', id: 1_452_453_066
mas 'HotKey', id: 975_890_633
mas 'iMovie', id: 408_981_434
mas 'Keynote', id: 409_183_694
mas 'Logic Pro', id: 634_148_309
mas 'Numbers', id: 409_203_825
mas 'Pages', id: 409_201_541
mas 'Playgrounds', id: 1_496_833_156
mas 'RunCat', id: 1_429_033_973
mas 'Transporter', id: 1_450_874_784
mas 'Xcode', id: 497_799_835
