[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'

[[plugins]]
build_on = '''
 ./install -all
 '''
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'previm/previm'

# ddc
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'Shougo/ddc-ui-native'
[[plugins]]
repo = 'Shougo/ddc-source-around'
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
[[plugins]]
repo = 'Shougo/ddu-kind-file'
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
[[plugins]]
repo = 'Shougo/ddu-source-file'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
