#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         off          \
    focus_follows_mouse         off          \
    window_origin_display       default      \
    window_placement            second_child \
    window_zoom_persist         on           \
    window_topmost              off          \
    window_shadow               on           \
    window_opacity              off          \
    window_opacity_duration     0.0          \
    window_animation_duration   0.0          \
    window_animation_frame_rate 120          \
    active_window_opacity       1.0          \
    normal_window_opacity       0.90         \
    window_border               off          \
    window_border_hidpi         on           \
    window_border_blur          off          \
    window_border_width         4            \
    window_border_radius        12           \
    active_window_border_color  0xff775759   \
    normal_window_border_color  0xff555555   \
    insert_feedback_color       0xffd75f5f   \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    mouse_modifier              fn           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap         \
    layout                      float        \
    top_padding                 0            \
    bottom_padding              0            \
    left_padding                0            \
    right_padding               0            \
    window_gap                  0

echo "yabai configuration loaded.."
