format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character\
"""
right_format = ''

add_newline = false

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '!'
staged = '+'
renamed = '»'
deleted = 'x'
typechanged = ""
