format = """
$directory\
$git_branch\
$character"""

right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell"""

add_newline = false

[aws]
disabled = true

[directory]
truncation_length = 10
truncation_symbol = "…"
fish_style_pwd_dir_length = 1

[character]
format = "$symbol "

[cmd_duration]
format = "[$duration]($style) "

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "

[hg_branch]
format = "[$symbol$branch]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[ruby]
format = "[$symbol($version)]($style) "

[rust]
format = "[$symbol($version)]($style) "

[time]
disabled = false
time_format = '%T'
format = '[$time]($style) '
