[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'junegunn/fzf'
dir = '~/.fzf_bin'
do = './install --all'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'ful1e5/onedark.nvim'
